#! /bin/bash -e

PAC=fk-digital-pdfjs
USER=fk-digital-pdfjs
GROUP=fk-digital
DGT_UID=9095
DGT_GID=9000

if [ "${1}" == "configure" ] ; then

    if ! getent group fk-digital > /dev/null; then
        groupadd -g ${DGT_GID} fk-digital
    fi

    if ! getent passwd ${DGT_UID} > /dev/null; then
        adduser --system --uid ${DGT_UID} --home /usr/share/$PAC --no-create-home --ingroup ${GROUP} --disabled-password --shell /bin/false $USER
    fi

    sudo mkdir -p /var/log/flipkart/fk-digital-pdfjs
    sudo mkdir -p /var/run/fk-digital-pdfjs
    sudo mkdir -p /usr/share/fk-digital-pdfjs
    sudo mkdir -p /etc/fk-digital-pdfjs
    sudo chown -R ${DGT_UID}:${DGT_GID} /etc/fk-digital-pdfjs
    sudo chown -R ${DGT_UID}:${DGT_GID} /usr/lib/${PAC}
    sudo chown -R ${DGT_UID}:${DGT_GID} /var/log/flipkart/fk-digital-pdfjs
    sudo chown -R ${DGT_UID}:${DGT_GID} /usr/share/fk-digital-pdfjs
    sudo chmod -R 777 /var/log/flipkart/fk-digital-pdfjs
    update-rc.d $PAC defaults
    /sbin/chkconfig --add $PAC
fi

